# Generated by Django 4.2.6 on 2023-10-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_courseforuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseforuser',
            name='user_name',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
