# Generated by Django 4.2.6 on 2023-10-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_courseforuser2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseForUser2',
        ),
        migrations.RemoveField(
            model_name='courseforuser',
            name='user_name',
        ),
    ]
